### ISSUE TITLE
One problem：panic: interface conversion: interface {} is nil, not []interface {}

### ISSUE THREAD

**Issue by hezhangke** [piaolin/fofa2Xray#12]
when I run it on win10, get the error of this。
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 1 [running]:
fofa2xray/utils.Fofa.Query(0xc000013140, 0xf, 0xc00000adc0, 0x20, 0xc0000052c0, 0x2, 0x2, 0xc0000131c0, 0x4, 0xc0000131e0, ...)
        /Volumes/KIOXIA_HJY/project/go/fofa2Xray/utils/fofa.go:39 +0x499
main.fofa()
        /Volumes/KIOXIA_HJY/project/go/fofa2Xray/main.go:133 +0x4d7
main.main()
        /Volumes/KIOXIA_HJY/project/go/fofa2Xray/main.go:75 +0x34d

**Comment by phplimin** [comment]
Have you solved your problem? I had the same problem. Please reply to me if you can solve the problem. Thank you!
