### ISSUE TITLE
请教一下，这个报错怎么解决？

### ISSUE THREAD

**Issue by yehecao** [piaolin/fofa2Xray#17]
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 1 [running]:
fofa2xray/utils.Fofa.Query({{0xc000016ac0, 0xf}, {0xc00001e540, 0x20}, {0xc0000727c0, 0x3, 0x4}, {0xc0
00016b38, 0x4}}, {0xc000016b60, ...})
        C:/Users/Alien/GolandProjects/fofa2Xray/utils/fofa.go:39 +0x365
main.main()
        C:/Users/Alien/GolandProjects/fofa2Xray/main.go:58 +0x5f3

**Comment by jjjxusbx** [comment]
work out!
